CREATE TABLE IF NOT EXISTS R_CURRENCY (
    ID INT IDENTITY(1,1) PRIMARY KEY,
    TITLE nvarchar(60) NOT NULL,
    CODE nvarchar(3) NOT NULL,
    VALUE numeric(18,2) NOT NULL,
    A_DATE date not null
);